import {
  DEFAULT_LOG_EXPOSURE,
  DEFAULT_LOG_VARIANCE,
  createProfileTemplate
} from '../utils/profile.js';

const MIN_LOG_EXPOSURE = Math.log(10);
const MAX_LOG_EXPOSURE = Math.log(1e11);

export const READING_TOPIC_LIBRARY = [
  '城市公园的晨练',
  '共享单车的利与弊',
  '校园咖啡馆的故事',
  '周末市集的风景',
  '社区图书馆的义工日记',
  '雨天的上海弄堂',
  '北京胡同里的老邻居',
  '夜跑俱乐部的挑战',
  '办公室里的健康小组',
  '家庭菜园的记录',
  '山城慢生活指南',
  '旅行中的小灾小难',
  '宠物领养日的忙碌',
  '民宿老板的心情笔记',
  '新手司机的高速初体验',
  '城市露营的准备',
  '旧书店复活计划',
  '手作面包坊的一天',
  '厨房里的减碳实验',
  '远程工作的日常',
  '跨城市恋爱的细节',
  '小区羽毛球社',
  '午休合唱团',
  '地铁上偶遇的友谊',
  '二次元社团的筹备',
  '独居青年的节俭妙招',
  '快闪咖啡车的旅程',
  '环保袋设计大赛',
  '小镇电影院重启记',
  '雨林保护志愿者',
  '外卖骑手的午后',
  '社区剧团排练记',
  '夜市摊主的创业路',
  '独立书店的会员沙龙',
  '长途列车上的对话',
  '城市天文观测夜',
  '初雪后的校园',
  '街区植物交换日',
  '国际学生的春节计划',
  '乡村快递员的心声',
  '音乐节志愿者手记',
  '周五的桌游之夜',
  '毕业旅行的预算',
  '晨跑者的播客list',
  '午后品茶会',
  '美术馆的亲子活动',
  '旧友重逢的聚餐',
  '自制蜡烛课堂',
  '合租公寓的规则',
  '创客空间的练习',
  '海边徒步的准备',
  '学生社团招新季',
  '青年设计师的展览',
  '城市骑行避暑路线',
  '合唱团的首演',
  '摄影散步社',
  '科学传播活动',
  '周末木工坊',
  '夜读俱乐部',
  '沉浸式剧场体验',
  '都市水彩速写',
  '新婚夫妻的搬家',
  '留学归来的分享会',
  '面包车改装计划',
  '夜市垃圾分类',
  '旅行播客的制作',
  '烹饪课堂的意外',
  '青年旅舍的值班夜',
  '小区共享花园',
  '海岛远程办公',
  '城市攀岩点',
  '亲子桌游营',
  '电影配乐沙龙',
  '剧本杀工作坊',
  '周末花艺体验',
  '地铁合唱团',
  '非遗手工课',
  '城市溜冰路线',
  '咖啡拼配研究',
  '网络读书会',
  '城市考古之旅',
  '新手露营事故',
  '长跑训练营',
  '校园二手市集',
  '猫咖的日常',
  '城市天台农场',
  '无人机摄影俱乐部',
  '城市森林散步',
  '独居青年的健身房',
  '咖啡车穿越老街',
  '安静离职的决定',
  '瑜伽与太极融合课',
  '自由职业者的作息',
  '夜班后的小确幸',
  '社区足球联赛',
  '快闪舞蹈活动',
  '旅行摄影人手记',
  '周末读书漂流',
  '城市奶茶探店',
  '植物医生的巡诊',
  '自行车维修教室',
  '城市拉力赛',
  '临海小镇的晨练'
];

export function createInitialState() {
  return {
    isFlipped: false,
    currentIndex: 0,
    lexicon: [],
    frequencyMap: {},
    frequencyProbabilityMap: {},
    activeCard: null,
    debugMode: true,
    isLoadingCard: false,
    errorMessage: '',
    isLoadingAudio: false,
    audioErrorMessage: '',
    audioBySentence: {},
    currentAudioUrl: '',
    studyMode: 'reading',
    listeningCardChance: 0.5,
    currentCardMode: 'reading',
    activeLevelMode: 'reading',
    activeCalibrationMode: null,
    appMode: null,
    isAuthenticated: false,
    calibrationComplete: false,
    lexiconLoaded: false,
    loginForm: {
      username: 'test-user',
      password: 'langy-demo',
      apiKey: '',
      error: ''
    },
    userProfile: {
      username: '',
      apiKey: ''
    },
    readingSegments: [],
    readingSentenceContexts: [],
    readingGlossesByKey: {},
    readingProcessing: false,
    readingGlossLoading: false,
    readingErrorMessage: '',
    readingLastAnalyzedAt: null,
    readingAnalyzedText: '',
    readingGeneration: {
      topic: '',
      difficultyTarget: 0.92,
      paragraphCount: 3,
      lifetimeTokensEstimate: 0,
      isGenerating: false,
      attempts: 0,
      maxAttempts: 3,
      passageText: '',
      passageStats: null,
      difficultyHistory: [],
      debugSteps: [],
      lastUsedTopic: ''
    },
    calibrationProfiles: {
      reading: createProfileTemplate(),
      listening: createProfileTemplate()
    },
    calibrationStatusByMode: {
      reading: '',
      listening: ''
    },
    logExposureMean: DEFAULT_LOG_EXPOSURE,
    logExposureVar: DEFAULT_LOG_VARIANCE,
    minLogExposure: MIN_LOG_EXPOSURE,
    maxLogExposure: MAX_LOG_EXPOSURE,
    exposuresForMastery: 8,
    totalCorpusFrequency: 1,
    recentLevelUpdates: [],
    maxRecentLevelUpdates: 12,
    totalResponses: 0,
    calibrationActive: false,
    calibrationResponses: [],
    calibrationQueue: [],
    calibrationSamplesTarget: 12,
    calibrationBuckets: [0.05, 0.15, 0.35, 0.55, 0.75],
    calibrationGridSize: 241,
    calibrationLogGrid: [],
    calibrationLogPosterior: [],
    calibrationPosterior: [],
    calibrationPosteriorMean: DEFAULT_LOG_EXPOSURE,
    calibrationPosteriorVar: DEFAULT_LOG_VARIANCE,
    calibrationPosteriorMedian: DEFAULT_LOG_EXPOSURE,
    calibrationPosteriorStdLog10: Number.POSITIVE_INFINITY,
    calibrationMedianIndex: 0,
    calibrationCredibleLowerIndex: 0,
    calibrationCredibleUpperIndex: 0,
    calibrationLastIndex: null,
    calibrationProbeCounts: {},
    calibrationStatusMessage: '',
    calibrationStdThreshold: 0.12,
    calibrationMaxSteps: 12,
    calibrationStepCount: 0,
    calibrationMinFrequencyProbability: 0,
    calibrationHistory: [],
    pendingCalibrationModes: [],
    targetSuccessRate: 0.5,
    targetWindowSize: 100,
    responseOptions: ['sentence', 'focus', 'unknown']
  };
}
